# Region 2 Configuration

replicaCount: 3

# iam with native eks oidc:
serviceAccount:
  annotations:
    # a role that can access the S3 bucket
    eks.amazonaws.com/role-arn: arn:aws:iam::211125428070:role/TwoRegionTest

# iam with kiam:
# podAnnotations:
#    # a role that can access the S3 bucket
#   iam.amazonaws.com/role: arn:aws:iam::211125428070:role/TwoRegionTest

resources:
  requests:
    cpu: 1m
    memory: 1

nodeName: ""
advertisedAddress: ""

env:
  # --------------------
  # common params
  # --------------------
  - name: RESTATE_LOG_FORMAT
    value: "json"
  - name: RESTATE_CLUSTER_NAME
    value: "two-region-demo-cluster"
  - name: RESTATE_AUTO_PROVISION
    value: "false"
  - name: RESTATE_ROLES
    value: '["worker","admin","metadata-server","log-server","http-ingress"]'
  - name: RESTATE_ROCKSDB_TOTAL_MEMORY_SIZE
    value: "1024MB"
  - name: RESTATE_WORKER__SNAPSHOTS__SNAPSHOT_INTERVAL_NUM_RECORDS
    value: "10000"
  - name: RESTATE_WORKER__EXPERIMENTAL_PARTITION_DRIVEN_LOG_TRIMMING
    value: "true"
  - name: RESTATE_WORKER__TRIM_DELAY_INTERVAL
    value: "15m"
  - name: RESTATE_DEFAULT_THREAD_POOL_SIZE
    value: "2"

  # --------------------
  # params that need to be overridden
  # --------------------
  - name: RESTATE_NODE_NAME
    value: $(POD_NAME).region2
  - name: RESTATE_LOCATION
    value: region2
  # this must match the format of the external-dns annotations in services.yaml
  - name: RESTATE_ADVERTISED_ADDRESS
    value: "http://$(POD_NAME).two-region-demo-cluster.restate.region2.dev.restate.cloud:5122"
  # the advertised addresses for all nodes need to be present in config for each node
  - name: RESTATE_METADATA_CLIENT__ADDRESSES
    value: >
      [
      "http://restate-0.two-region-demo-cluster.restate.region1.dev.restate.cloud:5122",
      "http://restate-1.two-region-demo-cluster.restate.region1.dev.restate.cloud:5122",
      "http://restate-2.two-region-demo-cluster.restate.region1.dev.restate.cloud:5122",
      "http://restate-0.two-region-demo-cluster.restate.region2.dev.restate.cloud:5122",
      "http://restate-1.two-region-demo-cluster.restate.region2.dev.restate.cloud:5122",
      "http://restate-2.two-region-demo-cluster.restate.region2.dev.restate.cloud:5122"
      ]
  # both regions talk to their local bucket for snapshots, cross region replication copies them across
  - name: RESTATE_WORKER__SNAPSHOTS__DESTINATION
    value: "s3://restate-two-region-test-region2/snapshots"
